### ISSUE TITLE
Work on Cesium view

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#1]
- [x] Get rid of any Cesium/Bing logos
- [x] Display view of the United States upon application start up
- [x] Limit zoom out
- [x] Remove other imagery options
- [x] Set home button to center to United States

**Comment by iplonk3** [comment]
Cesium actually does allow users to search by airport code. When a location is entered, Cesium zooms into this location and shows a birds-eye view of the area. We should limit searches to be strictly to airports.

**Comment by iplonk3** [comment]
I was playing around with ForeFlight some, and it does all you to zoom out and view the globe like Cesium. Instead of focusing on a flat view, I think we should get it to center to the United States upon opening, and we should limit how far the user can zoom out (i.e. the user should not be able to make the Earth look so far away on the screen but should be able to view the global as a whole). [Here](https://gis.stackexchange.com/questions/144361/how-to-set-the-coordinates-at-which-cesium-viewer-is-centered) is a link to a forum post asking about centering the view upon start up. We can use the [geographic center](https://en.wikipedia.org/wiki/Geographic_center_of_the_contiguous_United_States) of the United States to mark the center of the view. I will edit the checklist above to match this.

**Comment by iplonk3** [comment]
Source for setting home button: https://stackoverflow.com/questions/28709007/how-to-set-the-default-view-location-cesium-1-6

**Comment by lusean** [comment]
Useful for remove logo:

https://groups.google.com/forum/#!searchin/cesium-dev/logo|sort:date/cesium-dev/dj0K0Xh9lGk/UBNxtOCaBwAJ

https://groups.google.com/forum/#!searchin/cesium-dev/logo|sort:date/cesium-dev/P7Yp-w-U16I/zaNJg7a7AAAJ
