### ISSUE TITLE
Determine where to host database

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#14]
Could we use the MySQL/PHP relational database system provided by the College of Computing, or do we need to look at external systems?

**Comment by iplonk3** [comment]
Could we use the MySQL/PHP relational database system provided by the College of Computing, or do we need to look at external systems?

**Comment by iplonk3** [comment]
https://hosting.gatech.edu/welcome-oit-web-hosting

https://www.drupal.org/docs/7/install/step-2-create-the-database

**Comment by lusean** [comment]
https://docs.djangoproject.com/en/2.0/ref/databases/#mysql-notes

https://devcenter.heroku.com/articles/django-app-configuration
