### ISSUE TITLE
Learn Django

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#21]

**Comment by dylanpatel95** [comment]
https://www.youtube.com/watch?v=qgGIqRFvFFk&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK

**Comment by dylanpatel95** [comment]
[https://www.youtube.com/watch?v=qgGIqRFvFFk&list=PL6gx4Cwl9DGBlmzzFcLgDhKTTfNLfX1IK](url)

**Comment by iplonk3** [comment]
Used the tutorial above to begin creating models for the database and learning about Django url routing
