### ISSUE TITLE
Custom search box

### ISSUE THREAD

**Issue by dylanpatel95** [iplonk3/automated-turbulence-detection#23]
- make the search box
- connect the search box to custom search list stored locally

**Comment by annalaura** [comment]
Option 1: Filter the search before we let Google Maps search 

- have a list of airport codes 

- figure out a way put a flag on the search button that we won't let them click unless is enabled

- flag is disabled until what they type matches an airport code 

- problems: does google maps search airport codes? how do we restrict the "search" button?

**Comment by dylanpatel95** [comment]
option 2: having a json file with all of the airport codes, airport names, longitude, latitude, and tying the searchbox to only search for places from that json file

**Comment by annalaura** [comment]
So the easiest solution, though I haven't tested it would be to restrict the search based upon the "types property" in the google places api. 
So we would match the three letters to just ones of "types" : [ "airport" ]

https://developers.google.com/maps/documentation/javascript/geocoding
https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingAddressTypes
https://developers.google.com/places/supported_types
https://maps.googleapis.com/maps/api/geocode/json?address=MIA%20airport

**Comment by annalaura** [comment]
https://developers.google.com/maps/documentation/javascript/examples/geocoding-component-restriction

**Comment by iplonk3** [comment]
What @annalaura  discussed if anyone wants to look into it: Problems: 
1. Airport is not a valid component restriction (e.g. country, zipcode) to narrow the search broadly
2. Airport is not supported by auto complete 
3. If we restrict by airport we have to restrict by meter 50,000 meterese == 31 miles 
4. Can't figure out a broad way to easy search by airport

5. Not sure how to disable the search button (to then add in the json object of airports)
6. Can't use google airports api as qpx is disabled in april

Solutions? 
Maybe change the pitching to let you search just in the US for some restriction
