### ISSUE TITLE
Connect Django to CoC database

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#26]

**Comment by iplonk3** [comment]
For making the connection: [Integrating Django with a Legacy Database](https://docs.djangoproject.com/en/2.0/howto/legacy-databases/)
For protecting DB access: [Django environ](https://django-environ.readthedocs.io/en/latest/)

**Comment by lusean** [comment]
https://mitchel.me/2016/settings-management-in-django/

**Comment by iplonk3** [comment]
Not recognizing username currently
[Using MySQL with Django Access Denied for User](https://stackoverflow.com/questions/11170133/using-mysql-with-django-access-denied-for-user-localhost)

**Comment by iplonk3** [comment]
Django got me shook with how easy it is to make requests to the database: [Django DB Queries](https://docs.djangoproject.com/en/2.0/topics/db/queries/).
