### ISSUE TITLE
Modify db table fields

### ISSUE THREAD

**Issue by lusean** [iplonk3/automated-turbulence-detection#34]
- Decimal values on certain variables
- Extra value for weather reports to hold airplane flight id

**Comment by williamsam1** [comment]
- Latitude and longitude: Bounded between [0, 180]. Keep 3 digits to the left, needs precision.
- Altitude: Bounded by ~100000. Keep 5 digits to the left. Does not need decimal precision.
-Wind speed: Bounded by ~1000. Keep 3 digits to the left. Needs precision.
-Wind speed: Bounded by ~100. Keep 2 digits to the left. Needs precision.

**Comment by lusean** [comment]
Bound values
https://stackoverflow.com/questions/33772947/django-set-range-for-integer-model-field-as-constraint
