### ISSUE TITLE
Determine visualization of turbulence reports

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#37]
We need to use the weather report to generate turbulence visualization on the frontend.

**Comment by iplonk3** [comment]
- [ ] Generate image from weather data. @williamsam1 
- [ ] Determine visualization of weather (color-coding). @lusean 
- [ ] Update image live. @me

**Comment by williamsam1** [comment]
Possible solution for live updating of overlay
https://developers.google.com/maps/documentation/javascript/examples/overlay-symbol-animate

**Comment by lusean** [comment]
https://www.aviationweather.gov/turbulence/help?page=plot
https://www.aviationweather.gov/turbulence/gtg

Can potentially add color legend in corner to map display

**Comment by iplonk3** [comment]
@lusean Could you work on coming up with a better way to display the turbulence information?

**Comment by iplonk3** [comment]
Need to determine proper color coding system for turbulence severity and create a legend for the user

**Comment by iplonk3** [comment]
Need to determine if there is a certain threshold where below this point no weather report is displayed on the map

**Comment by iplonk3** [comment]
Look for continuous coloring function with d3

**Comment by lusean** [comment]
Add color scale legend to map

**Comment by lusean** [comment]
Experiment with opacity of turbulence points

**Comment by iplonk3** [comment]
@williamsam1 @lusean Do we want to label the scale as TKE or turbulence severity? I haven't been able to find what TKE values corresponds to what EDR values. I know turbulence severity would mean more to the user and likely Pickell, but I am not sure how to determine if we are labeling them properly. I found this [d3 legend maker](http://d3-legend.susielu.com/#color-linear-custom). It would be useful if we choose numerical values to display. 
![screen shot 2018-04-10 at 10 59 39 am](https://user-images.githubusercontent.com/14985857/38565116-759215b8-3cae-11e8-834c-a41b85ebf35d.png)
