### ISSUE TITLE
Make GET request to server to obtain weather reports

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#42]

**Comment by iplonk3** [comment]
https://www.w3schools.com/js/js_json_http.asp

**Comment by williamsam1** [comment]
[Commit message](https://github.com/iplonk3/automated-turbulence-detection/commit/72b7be21c88634e23215c1831cfb1553a6307fcb) details current JSON GET request format for table entries.

**Comment by iplonk3** [comment]
On client side should look something like this:
```javascript
function makeQuery(max, start, table) {
    var xhttp = new XMLHttpRequest();
    xhttp.open("GET", "http://127.0.0.1:8000/", true);
    xhttp.send("max=" + max + "&start=" + start + "&table=" + table);
    xhttp.onreadystatechange = processRequest;

    function processRequest(e) {
        if (xhttp.readyState === 4 && xhttp.status === 200) {
            var response = JSON.parse(xhttp.response);
            return response.entries;
        }
    }
}
```
Need to include `local_manage.py` in **simulation** branch before this can be tested or merge **simulation** with **master**

**Comment by iplonk3** [comment]
Here is the [commit](https://github.com/iplonk3/automated-turbulence-detection/commit/13da4711cf7b142b9fadfc59ee17baa2f08d90e7) for the request on the client side. Right now, you press a button, and five markers are displayed in the locations of the weather reports to demonstrate the connection. This will change when we switch to D3.

**Comment by iplonk3** [comment]
Example of what is returned by the server side (specifically reports) for future reference:
```JSON
{
    "entries": [
        {
            "id": 5662,
            "time": "2017-08-01T00:00:25.248Z",
            "latitude": "33.530990",
            "longitude": "-88.328869",
            "altitude": "6000.0",
            "aircraft_type": 247,
            "wind_x": "-1.802",
            "wind_y": "0.572",
            "tke": "0.2003"
        }
    ]
}
```
