### ISSUE TITLE
Add button to toggle turbulence

### ISSUE THREAD

**Issue by iplonk3** [iplonk3/automated-turbulence-detection#5]
There should be a button to toggle the turbulence display.

**Comment by iplonk3** [comment]
@williamsam1 created a button, but it would be nice for it to be on the upper righthand corner with the other controls.

Resources
- [Sandcastle - New button](https://github.com/AnalyticalGraphicsInc/cesium/issues/1898)
- [How to put a button at the top of Cesium panel?](https://groups.google.com/forum/#!topic/cesium-dev/400HuvVInLM)
- [Adding a button](https://groups.google.com/forum/#!topic/cesium-dev/_xgDaxhMm5o)

**Comment by williamsam1** [comment]
Button is injected into the toolbar with the other controls via JavaScript. Added checkbox to show status of image.
